### ISSUE TITLE
Better exception handling of bad calls to import CDAS, use of custom exception rather than ValueError, AttributeError

### ISSUE THREAD

**Issue by marek-cottingham** [TheMuonNeutrino/magSonify#18]

**Comment by marek-cottingham** [comment]
1) Example event value error: 2007-09-24 00:00:00 to 2007-09-24 12:00:00

File "~~~~\magSonify\MagnetometerData.py", line 192, in _importCdasPeem
    data = cdas.get_data(
  File "C:\Python39\lib\site-packages\ai\cdas.py", line 306, in get_data
    table = rdr.read(data_path)
  File "C:\Python39\lib\site-packages\astropy\io\ascii\core.py", line 1274, in read
    self.header.get_cols(self.lines)
  File "C:\Python39\lib\site-packages\astropy\io\ascii\core.py", line 600, in get_cols
    raise ValueError('No header line found in table')
ValueError: No header line found in table

**Comment by marek-cottingham** [comment]
2. Example event attribute error: 2008 12 08 to 2008 12 09 - Sat B

Traceback (most recent call last):
 15% [...........                                                               ]  786432 / 5038785  File "C:\Python39\lib\threading.py", 
line 954, in _bootstrap_inner
 16% [...........                                                               ]  811008 / 5038785    self.run()
  File "C:\Python39\lib\threading.py", line 892, in run
 16% [............                                                              ]  835584 / 5038785    self._target(*self._args, **self._kwargs)
portCdasMagneticField
 16% [............                                                              ]  851968 / 5038785    data[f"BX_FGS-{satellite}"],       
KeyError: 'BX_FGS-B'
100% [..........................................................................] 5038785 / 5038785
Traceback (most recent call last):
  File "~~~~\pySonify\Example Code\devInterProcessCommunication.py", line 39, in <module>
    mag.defaultProcessing()
  File "~~~~\magSonify\MagnetometerData.py", line 231, in defaultProcessing
    self.magneticField.removeDuplicateTimes()
AttributeError: 'NoneType' object has no attribute 'removeDuplicateTimes'

**Comment by marek-cottingham** [comment]
Need to implement tests for these
